DATA_DOWNLOAD_PATH: "../data/sc/"
DATA_PATH: "../data/sc/SpeechCommands/speech_commands_v0.02"
PICKLE_PATH: "../simple_pickles/"
AUDIO_PATH: "../audio/"
EXPERIMENTS_PATH: "../experiments/"

should_repickle: False
should_train_model: False

device: "cuda"

log_interval: 100

dummy_data_length: 

epochs: 10
batch_size: 128
lr: 0.1
lr_step_size: 1
lr_gamma: 0.5
weight_decay: 0.0001
sqrt_for_loss : True

model_type: "conv2d_vae"
latent_dim: 32
channels : [16, 32, 64, 64,64,128,128]
strides : [[1,2],[1,2],[1,2],[2,1],[2,1],[2,1]]
kernel_sizes : [[1,3],[1,3],[1,3],[3,1],[3,1],[3,1]]
paddings : [[0,1],[0,1],[0,1],[1,0],[1,0],[1,0]]
# paddings: [0,0,0,0,0,0]


condition_dec : True
condition_enc : True
classify : True

nonlinearity : "tanh"
batch_norm : True


experiment_name: "exp14"

n_mels: 64
mel_scale: "htk"
n_fft: 512
hop_length: 256
win_length: 512

# n_mels: 81
# mel_scale: "htk"
# n_fft: 400
# hop_length:
# win_length:

transform_type: "mel_spectrogram"
