DATA_DOWNLOAD_PATH: "../data/sc/"
DATA_PATH: "../data/sc/SpeechCommands/speech_commands_v0.02"
PICKLE_PATH: "../simple_pickles/"
AUDIO_PATH: "../audio/"
EXPERIMENTS_PATH: "../experiments/"

should_repickle: False
should_train_model: True

device: "cuda"

log_interval: 100

dummy_data_length: -1

epochs: 100
batch_size: 128
lr: 0.1
lr_step_size: 10
lr_gamma: 0.5
weight_decay: 0.0001

model_type: "conv2d_vae"
latent_dim: 32
channels : [16, 32, 64, 128]
strides : [[2,1],[2,1],[2,1],[2,1]]
kernel_sizes : [[3,5],[3,5],[3,5],[3,5],]
paddings : [[1,2],[1,2],[1,2],[1,2],]


nonlinearity : "tanh"
batch_norm : True


experiment_name: "exp12_stride_over_features"

n_mels: 13
mel_scale: "htk"
n_fft: 400
hop_length: 256
win_length: 400

# n_mels: 81
# mel_scale: "htk"
# n_fft: 400
# hop_length:
# win_length:

transform_type: "mel_spectrogram"
