DATA_DOWNLOAD_PATH: "../data/sc/"
DATA_PATH: "../data/sc/SpeechCommands/speech_commands_v0.02"
PICKLE_PATH: "../simple_pickles/"
AUDIO_PATH: "../audio/"
EXPERIMENTS_PATH: "../experiments/"

should_repickle: False
should_train_model: True
continue_training: True

device: "cuda"

log_interval: 100

dummy_data_length: 

epochs: 25
batch_size: 128
lr: 0.01
lr_step_size: 5
lr_gamma: 0.1
weight_decay: 0.0001
log_input: False

model_type: "conv1d_vae"
latent_dim: 512
channels : [64,8]
# channels : [4,8,16, 32]
strides : [4,16]
kernel_sizes : [128,64]
paddings : [0,0]
# paddings: [0,0,0,0,0,0]


condition_dec : True
condition_enc : False
classify : False

nonlinearity : "tanh"
batch_norm : True

experiment_name: "exp25"

n_mels: 64
mel_scale: "htk"
n_fft: 512
hop_length: 256
win_length: 512

# n_mels: 81
# mel_scale: "htk"
# n_fft: 400
# hop_length:
# win_length:

transform_type: 
