DATA_DOWNLOAD_PATH: "../data/sc/"
DATA_PATH: "../data/sc/SpeechCommands/speech_commands_v0.02"
PICKLE_PATH: "../simple_pickles/"
AUDIO_PATH: "../audio/"
EXPERIMENTS_PATH: "../experiments/"

should_repickle: False
should_train_model: True

device: "cuda"

log_interval: 10

epochs: 2
batch_size: 256

model_type: "linear_vae"
latent_dim: 256
hidden_dims: [1024, 512, 512]

experiment_name: "exp3"

# n_mels: 80
# mel_scale: "htk"
# n_fft: 400
# hop_length: 256
# win_length: 400
# n_stft: n_fft // 2 + 1

n_mels: 39
mel_scale: "htk"
n_fft: 400
hop_length: None
win_length: None
