DATA_DOWNLOAD_PATH: "../data/sc/"
DATA_PATH: "../data/sc/SpeechCommands/speech_commands_v0.02"
PICKLE_PATH: "../simple_pickles/"
AUDIO_PATH: "../audio/"
EXPERIMENTS_PATH: "../experiments/"

should_repickle: True
should_train_model: True

device: "cuda"

log_interval: 100

epochs: 100
batch_size: 1024
lr: 0.1
lr_step_size: 10
lr_gamma: 0.1
weight_decay: 0.0001

model_type: "conv2d_vae"
latent_dim: 256
channels : [4, 8, 16, 32]
strides : [1, 2, 2, 2]
kernel_sizes : [3, 3, 3, 3]
paddings : [1, 1, 1, 1]


nonlinearity : "relu"
batch_norm : True


experiment_name: "exp6"

# n_mels: 80
# mel_scale: "htk"
# n_fft: 400
# hop_length: 256
# win_length: 400
# n_stft: n_fft // 2 + 1

n_mels: 81
mel_scale: "htk"
n_fft: 400
hop_length:
win_length:
